name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test sourcer.source.sh
      run: cd test; ./sourcer.source_test.sh
    - name: Test sourcer.build.source.sh
      run: cd test; ./sourcer.build.source_test.sh

	test-16-04:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Test sourcer.source.sh
      run: cd test; ./sourcer.source_test.sh
    - name: Test sourcer.build.source.sh
      run: cd test; ./sourcer.build.source_test.sh


